---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)

repo_path <- "tennessee-ev-chargers"
suppressWarnings(suppressMessages(source(paste0(repo_path, "/manifest.R"))))
```


```{r}
sf_county <-
  read_sf(paste0(repo_path,
                 "/data/county/01_county-shape-file.shp")) %>% 
  st_transform(crs = 4326) %>% 
  filter(statefp == "47") %>% 
  left_join(tn_wide, by = "geoid")

alt_fuel_stations_tn <- 
  read_csv("tn-chargers/data/alt_fuel_stations.csv") %>%
  janitor::clean_names() %>%
  filter(state == "TN" & fuel_type_code == "ELEC") %>%
  select(station_name, street_address, city, zip, cards_accepted, 
         latitude, longitude)
```


```{r}
nashville_stations <- 
  alt_fuel_stations_tn %>% 
  filter(city == "Nashville") %>% 
  mutate(unique_stations = stringr::word(station_name, 1,2, sep=" ")) %>% 
  select(unique_stations, latitude, longitude) %>%
  unique()

tn_chargers_leaflet <- 
  leaflet(nashville_stations) %>% 
    addTiles() %>% 
    addCircleMarkers(
        data = nashville_stations, color = ~chargingtypeColor(unique_stations),
        lat = ~latitude, lng = ~longitude, 
        popup = paste(nashville_stations$station_name)
    )


# for printing the maps
htmltools::tagList(tn_chargers_leaflet)
```

