---
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)

repo_path <- "tennessee-ev-chargers"
suppressWarnings(suppressMessages(source(paste0(repo_path, "/manifest.R"))))
suppressWarnings(suppressMessages(source(paste0(repo_path, "/move-ak-hi.R"))))
```

# Import income data for TN and location data for EV chargers.
```{r, warning = FALSE, message = FALSE}
tn_wide <- 
  read_csv(paste0(repo_path, "/data/tn_medianincome_2019.csv")) %>% 
  janitor::clean_names() %>% 
  mutate(geoid = paste0(geoid))

# Downloaded from https://www.huduser.gov/portal/datasets/usps_crosswalk.html
zip_tract_xwalk <- 
  readxl::read_xlsx(paste0(repo_path, "/data/ZIP_TRACT_122019.xlsx")) %>%
  janitor::clean_names() %>% 
  rename(geoid = tract)

sf_county <-
  read_sf(paste0(repo_path,
                 "/data/county/01_county-shape-file.shp")) %>% 
  st_transform(crs = 4326) %>% 
  filter(statefp == "47") %>% 
  left_join(tn_wide, by = "geoid")

sf_cbsa <- 
  read_sf(paste0(repo_path, "/data/CBSA-2010-16i4k3s/CBSA10.shp")) %>% 
  st_transform(crs = 4326) 

alt_fuel_stations_tn <- 
  read_csv("tn-chargers/data/alt_fuel_stations.csv") %>%
  janitor::clean_names() %>%
  filter(state == "TN" & fuel_type_code == "ELEC") %>%
  select(station_name, street_address, city, zip, cards_accepted, latitude, longitude)

alt_fuel_stations_davidson <- 
  alt_fuel_stations_tn %>%
  filter(city == "Nashville")  %>%
  mutate(unique_stations = stringr::word(station_name, 1,2, sep=" ")) %>% 
  select(unique_stations,station_name, latitude, longitude,street_address, city, zip) %>%
  unique() %>% 
  mutate(charger_type = ifelse(grepl("METRO", station_name, ignore.case = T),
                               "Metro", station_name)) %>% 
  mutate(charger_type = ifelse(grepl("PREMIER", station_name, ignore.case = T), 
                               "Premier Parking", charger_type)) %>% 
  mutate(charger_type = ifelse(grepl("BNA|Terminal Dr", street_address, ignore.case = T), 
                               "Airport", charger_type)) %>% 
  mutate(charger_type = ifelse(grepl("BNA|AIRPORT", station_name, ignore.case = T), "Airport",
                               charger_type)) %>% 
  mutate(charger_type = ifelse(grepl("CHPT", station_name, ignore.case = T), "Chargepoint",
                               charger_type)) %>% 
  mutate(charger_type = ifelse(grepl("Nissan|BMW", station_name, ignore.case = T), "Car dealer",
                               charger_type)) %>% 
  mutate(charger_type = ifelse(grepl("University", station_name, ignore.case = T), "University",
                               charger_type)) %>% 
  mutate(charger_type = ifelse(grepl("Marriott|Loews|Duke|Aertson", 
                                     station_name, ignore.case = T), "Hotel",
                               charger_type)) %>% 
  mutate(charger_type = ifelse(grepl("Shay|Windsor|Rivertop|Apex|oneC1T|Eleven North",
                                     station_name, ignore.case = T), "Apartment complex",
                               charger_type))  %>%
  mutate(charger_type = ifelse(grepl("Tesla", station_name, ignore.case = T),
                               "Tesla", charger_type)) %>% 
  mutate(charger_type = ifelse(grepl("Vanderbilt|TCMC|TriStar",
                                     station_name, ignore.case = T),
                               "Hospital", charger_type)) %>% 
  mutate(charger_type = ifelse(grepl("WHOLEFOODS|TARGET|Publix|Mapco",
                                     station_name, ignore.case = T),
                               "Grocery store", charger_type)) %>%
  mutate(charger_type = ifelse(grepl("Willowbrook", station_name, ignore.case = T),
                                "Retail space", charger_type)) %>%
  mutate(charger_type = ifelse(grepl("State Park", station_name, ignore.case = T),
                                "State Park", charger_type)) %>%
  mutate(charger_type = str_trim(charger_type)) %>%
  mutate(len_name = str_length(charger_type)) 
  
fix_names <- 
  alt_fuel_stations_davidson %>% 
  filter(!(charger_type %in% c("Metro", "Premier Parking", "Chargepoint", "Car dealer", "Tesla",
                               "Hotel", "University","Apartment", "Airport", "Grocery store",
                               "Hospital", "Apartment complex", "Retail space", "State Park"))) %>%
  filter(len_name > 10)

ev_stations_davidson_ <-
  alt_fuel_stations_davidson %>% 
  filter(charger_type %in% c("Metro", "Premier Parking", "Chargepoint", "Car dealer", "Tesla",
                               "Hotel", "University","Apartment", "Airport", "Grocery store",
                               "Hospital", "Apartment complex", "Retail space"))
  
```


```{r, warning = FALSE, message = FALSE}
# Counties
tn_income_plt <-
  sf_county %>%
  ggplot() + 
  geom_sf(aes(fill = medinc_e)) +
  scale_fill_gradient2(low = scales::muted("blue"),
                       mid = "white",high = scales::muted("red"),
                       midpoint = 44122,limits = c(0,150000)) + 
  coord_sf(datum=NA) + 
  labs(fill="") + 
  ggtitle("Tennessee Median Income by county, 2019") + 
  ggthemes::theme_tufte(base_family = "Gill Sans")

# ggsave(tn_income_plt,
#        filename = paste0(repo_path, "/output/tn_income_2019.png"), 
#        width = 8, height = 4)

tn_ev_charger_locations <-
  tn_income_plt + 
  geom_point(data = alt_fuel_stations_tn, aes(x=longitude,y=latitude)) + 
  labs(title = "",
       caption = "Data source: \n2019 Median Household Income Data from the American Community Survey. census.gov/programs-surveys/acs/. \nEV coordinates obtained using the National Renewable Energy Lab API. developer.nrel.gov. \nEach dot represents a terminal of one or more EV chargers") +
  theme_tufte_revised() +
  labs(fill = "Median Income") +
  theme(
    plot.caption = element_text(size = 12, hjust = 0),
    axis.title.x=element_blank(),
    axis.title.y=element_blank(), plot.caption.position =  "plot"
  ) 
  
# ggsave(tn_ev_charger_locations,
#        filename = paste0(repo_path, "/output/tn_ev_charger_locations_income_2019.png"),
#        width = 8, height = 4)

```


```{r, warning = FALSE, message = FALSE}
tn_chargers_leaflet <- 
  leaflet(alt_fuel_stations_davidson) %>% 
  addTiles() %>% 
  addCircleMarkers(data = alt_fuel_stations_davidson,
                   lat = ~latitude, lng = ~longitude, 
        popup = paste(alt_fuel_stations_davidson$unique_stations)
    )

saveWidget(tn_chargers_leaflet, file = paste0(repo_path,"/output/tn_chargers.html"))

# for printing the maps
htmltools::tagList(tn_chargers_leaflet)
# htmlwidgets::saveWidget(frameableWidget(tn_chargers_leaflet),
#                         paste0(repo_path,"/output/tn_chargers.html"))
```


```{r}
library(tigris)

cb_tn <- core_based_statistical_areas(year = 2018, cb = TRUE)
davidson.metro <- filter(cb_tn, grepl("Davidson", NAME))
  
# If you want to use predefined palettes in the RColorBrewer package:
# Call RColorBrewer::display.brewer.all() to see all possible palettes
pal <- colorFactor(palette = 'Set3', domain = alt_fuel_stations_davidson$charger_type)

davidson_chargers_leaflet <- 
  leaflet(davidson.metro) %>% 
    addTiles() %>% 
    addCircleMarkers(data = alt_fuel_stations_davidson,
                     lat = ~latitude, lng = ~longitude,  color = ~pal(charger_type),
                     popup = paste(alt_fuel_stations_davidson$unique_stations, "<br>",
                                   alt_fuel_stations_davidson$charger_type, "<br>",
                                   alt_fuel_stations_davidson$street_address, "<br>",
                                   alt_fuel_stations_davidson$city, " ",
                                   alt_fuel_stations_davidson$zip)
                     ) %>%
  addLegend(data = alt_fuel_stations_davidson, 
            pal = pal, values = ~charger_type,group = "circles",
            position = "bottomleft" ) %>%
  addLayersControl(overlayGroups = c("circles"))
```

